config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  root 'static_pages#home'

  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup' => 'users#new'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :relationships, only: [:create, :destroy]
  resources :microposts do
    resources :comments, only: [:create, :destroy] do
      post 'mark', to: 'marks#create'
      delete 'mark', to: 'marks#destroy'
    end

    post 'mark', to: 'marks#create'
    delete 'mark', to: 'marks#destroy'
  end

  resources :notifications, only: [:index]
  resources :hashtag_subscriptions, only: [:create, :destroy]
  resources :hashtags, only: [:index, :destroy, :show]
end

app/models/hashtag.rb
class Hashtag < ApplicationRecord
  validates :name, presence: true, uniqueness: true, format: { without: /\s/ }

  has_many :micropost_hashtags, dependent: :destroy
  has_many :microposts, through: :micropost_hashtags
  has_many :subscriptions, class_name: 'HashtagSubscription', dependent: :destroy
  has_many :subscribers, through: :subscriptions, source: :user
end

app/controllers/hashtags_controller.rb
# frozen_string_literal: true

class HashtagsController < ApplicationController
  before_action :logged_in_user
  before_action :admin_user, only: [:destroy]

  def index
    search = params[:q]
    @hashtags = if search.blank?
                 Hashtag.paginate(page: params[:page])
               else
                 Hashtag.where('name ILIKE :search', search: "%#{search}%").paginate(page: params[:page])
               end
  end

  def show
    @hashtag = Hashtag.find(params[:id])
    @microposts = @hashtag.microposts.paginate(page: params[:page])
  end

  def destroy
    Hashtag.find(params[:id]).destroy
    flash[:success] = 'Hashtag was deleted'
    redirect_to hashtags_url
  end
end

app/views/hashtags/_hashtag.html.erb
<li>
  <%= link_to hashtag.name, hashtag_path(hashtag) %> |
  <% if current_user.subscribed_hashtags.include?(hashtag) %>
    <%= link_to "Unfollow", hashtag_subscription_path(hashtag.id), method: :delete %>
  <% else %>
    <%= link_to "Follow", hashtag_subscriptions_path(hashtag_name: hashtag.name), method: :post %>
  <% end %>
  <% if current_user.is_admin? %>
    | <%= link_to 'delete', hashtag, method: :delete, data: { confirm: 'Are you sure?' } %>
  <% end %>
</li>

app/views/hashtags/index.html.erb
<% provide(:title, 'All hashtags') %>
<h1>All hashtags</h1>

<%= turbo_frame_tag 'hashtag_listings' do %>
  <ul class="users">
    <%= form_with url: hashtags_path,
                  method: :get,
                  data: { turbo_frame: 'hashtag_listings' },
                  html: { class: 'form-inline' } do |form| %>
      <%= form.search_field :q, class: 'form-control', placeholder: 'Search for a hashtag...' %>
      <% if params[:q].present? %>
        <%= link_to 'Clear',
                    hashtags_path,
                    class: 'btn btn-outline-danger',
                    style: 'margin-bottom: 15px;',
                    data: { turbo_frame: 'hashtag_listings' } %>
      <% end %>
    <% end %>
    <%= render @hashtags %>
  </ul>
<% end %>

<%= will_paginate %>

app/views/hashtags/show.html.erb
<% provide(:title, "#{@hashtag.name}") %>

<h1>#<%= @hashtag.name %> posts</h1>

<ol class="microposts">
  <%= render @microposts %>
</ol>

<%= will_paginate @microposts %>