config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  root 'static_pages#home'

  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup' => 'users#new'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :relationships, only: [:create, :destroy]
  resources :microposts do
    resources :comments, only: [:create, :destroy] do
      post 'mark', to: 'marks#create'
      delete 'mark', to: 'marks#destroy'
    end

    post 'mark', to: 'marks#create'
    delete 'mark', to: 'marks#destroy'
  end

  resources :notifications, only: [:index]
  resources :hashtag_subscriptions, only: [:create, :destroy]
  resources :hashtags, only: [:index, :destroy, :show]
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://localhost:3000/">Microblog</a>
    by <a href="mailto:egor.dorosh02@icloud.com">Egor Doroshenko</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to 'About', about_path %></li>
      <li><%= link_to 'Contact', contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to 'Microblog', root_path, id: 'logo' %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Home', root_path %></li>
        <li><%= link_to 'Help', help_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li><%= link_to "Hashtags", hashtags_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Profile', current_user %></li>
              <li><%= link_to 'Notifications', notifications_path %></li>
              <li><%= link_to 'Settings', edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li><%= link_to 'Log out', logout_path, method: 'delete' %></li>
            </ul>
          </li>
          <li>
            <%= link_to notifications_path do %>
              <% if current_user.unread_notifications_count > 0 %>
                    <span class="badge bg-danger notification-counter">
                      <%= pluralize(current_user.unread_notifications_count, 'notification') %>
                    </span>
              <% end %>
            <% end %>
          </li>
        <% else %>
          <li><%= link_to 'Log in', login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.11.3/css/lightbox.min.css" %>
    <%= javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.11.3/js/lightbox.min.js" %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>